version: 2
jobs:
  build:
    docker:
      - image: node:8.9
    steps:
      - checkout
      - run:
          name: Install dependences
          command: npm install
      - run:
          name: Test
          command: npm test
